### ISSUE TITLE
panic: sync: negative WaitGroup counter

### ISSUE THREAD

**Issue by daymade** [daymade/etcd-cache#1]
```
panic: sync: negative WaitGroup counter

goroutine 1 [running]:
sync.(*WaitGroup).Add(0xc00020a050, 0xffffffffffffffff)
	/usr/local/go/src/sync/waitgroup.go:74 +0x135
sync.(*WaitGroup).Done(...)
	/usr/local/go/src/sync/waitgroup.go:99
github.com/daymade/etcd-cache.Sync(0x16945d5, 0x1, 0x176ff40, 0xc0000b4280, 0x16c23f0, 0xc000186000, 0xc00020a050)
	github.com/daymade/etcd-cache/cache.go:56 +0x506
```

**Comment by daymade** [comment]
usage example:

```go
	wg.Add(1)

	cache.Sync("/", backend, logFunc, cli, &wg)

	wg.Wait()
```
